name: scheduler_base
description: base classes for the scheduler
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  intl: ^0.15.0

dev_dependencies:
  test: ^1.5.0