name: scheduler_base
description: base classes for the scheduler
version: 0.0.1
publish_to: none

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  intl: ^0.14.0
  dson: ^0.3.4

dev_dependencies:
  test: ^0.12.0
